### ISSUE TITLE
config.status: error: cannot find input file: `Makefile.in'

### ISSUE THREAD

**Issue by amiduai** [CAIDA/mper#3]
I was trying  installing mper on my Ubuntu 18.04, but After I typed "sudo ./configure" in the terminal, I got this error message:
"  config.status: error: cannot find input file: `Makefile.in'   ",
I don't know what does it mean, and what should I do now?

**Comment by avinen** [comment]
If you're building from a clone of the repository (vs. from a package for an actual release), then you'll have to do an additional step before running configure:

$ ./ac_prepare.sh

That will create various files needed to configure and build mper.

By the way, you don't need to run configure with sudo.  If you want to install mper in a directory that requires root access, then you can run "make install" with sudo.

**Comment by lvmy3** [comment]
I have addressed this problem using automake, you can try $ aclocal & automake --add-missing & autoconf.
However, I still can't compile the MIDAR with error:
midar-targets.cc:366:39: error: no match for ‘operator!=’ (operand types are ‘const Sink’ and ‘const Sink’)
Has anyone met this issue before?

**Comment by avinen** [comment]
> However, I still can't compile the MIDAR with error:
> midar-targets.cc:366:39: error: no match for ‘operator!=’ (operand types are ‘const Sink’ and ‘const Sink’)
> Has anyone met this issue before?

Fortunately, there's already a fix for this committed into master:

https://github.com/CAIDA/alias-resolution/commit/7e83dd0836cdd02d63d755c5edc18db0c14ebecb

Could you please try building from the latest repo?

**Comment by lvmy3** [comment]
Thanks. But I can't find the repository you mentioned with 404 error.  Thank you again.

> > However, I still can't compile the MIDAR with error:
> > midar-targets.cc:366:39: error: no match for ‘operator!=’ (operand types are ‘const Sink’ and ‘const Sink’)
> > Has anyone met this issue before?
> 
> Fortunately, there's already a fix for this committed into master:
> 
> [CAIDA/alias-resolution@7e83dd0](https://github.com/CAIDA/alias-resolution/commit/7e83dd0836cdd02d63d755c5edc18db0c14ebecb)
> 
> Could you please try building from the latest repo?

**Comment by avinen** [comment]
Sorry, you're right--the repo is private right now.  Let me see what I can do to get you going.

**Comment by avinen** [comment]
MIDAR v0.8.0 is now released with fixes to various C++ compiler incompatibilities.
https://www.caida.org/tools/measurement/midar/

**Comment by lvmy3** [comment]
> MIDAR v0.8.0 is now released with fixes to various C++ compiler incompatibilities.
> https://www.caida.org/tools/measurement/midar/

Thanks a lot!

**Comment by l0nl1f3** [comment]
> MIDAR v0.8.0 is now released with fixes to various C++ compiler incompatibilities. https://www.caida.org/tools/measurement/midar/

Just ran into the same issure while building MIDAR v0.7.1, is the new version published somewhere else? The link given only has 0.7.1.

**Comment by amacaida** [comment]
MIDAR v0.8.0 is only released in a beta form as we do not have the resources to work on MIDAR in recent years.

Download it at https://www.caida.org/catalog/software/midar/downloads/midar-0.8.0-beta1.tar.gz

**Comment by amacaida** [comment]
MIDAR v.0.8.0 can be downloaded at https://www.caida.org/catalog/software/midar/downloads/midar-0.8.0.tar.gz
